# Generated by Django 6.0.1 on 2026-01-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='wallet1', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
