# Generated by Django 6.0.1 on 2026-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_wallet_wallet_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='coin',
            field=models.CharField(default='€', max_length=1),
            preserve_default=False,
        ),
    ]
