# Generated by Django 6.0.1 on 2026-01-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_ismonthly_delete_monthlyexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='isMonthly',
            new_name='is_monthly',
        ),
    ]
