# Generated by Django 6.0.1 on 2026-01-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_ismonthly_expense_is_monthly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_monthly',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='One-time', max_length=10),
        ),
    ]
