# Generated by Django 6.0.1 on 2026-01-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_expense_is_monthly_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='last_deduction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
